Repository monizb/hacktoberfest-swag-list, pull requests merged in 2022-10, with the labels that each got.

#138 Flyte Added
  src/list.json
Labels: hacktoberfest, hacktoberfest-accepted, swag

#140 added INVERTASE
  src/list.json
Labels: hacktoberfest, hacktoberfest-accepted

#141 Remove duplicate description tag
  public/index.html
Labels: bug, hacktoberfest, hacktoberfest-accepted

#154 Added swag in list.json
  src/list.json
Labels: hacktoberfest, hacktoberfest-accepted, swag

#153 Added servicenow swag
  src/list.json
Labels: hacktoberfest, hacktoberfest-accepted

#149 docker added
  src/list.json
Labels: hacktoberfest, swag

#165 Added Codedamn Swag
  src/list.json
Labels: hacktoberfest-accepted

#170 added Pusher Hacktoberfest Contribution json list
  src/list.json
Labels: hacktoberfest-accepted

#151 added ClueLess Community to list
  src/list.json
Labels: hacktoberfest-accepted

#156 Added UnionML Swags
  src/list.json
Labels: hacktoberfest-accepted, swag

#157 Emoji's & Color changes
  src/Utils/getTagColor.js
  src/Utils/getTagEmoji.js
  src/list.json
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#172 New Opportunity StepZen
  src/list.json
Labels: hacktoberfest-accepted

#194 add swag event info for Mattermost Hacktoberfest 2022
  src/list.json
Labels: hacktoberfest, hacktoberfest-accepted

#189 Adding local stack
  src/list.json
Labels: hacktoberfest-accepted

#198 Added Uno Platform Swag
  src/list.json
Labels: hacktoberfest-accepted

#199 Added Novu challenge
  src/list.json
Labels: hacktoberfest-accepted

#200 feat: Add refine event for hacktoberfest
  src/list.json
Labels: hacktoberfest-accepted
